/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NodeLlmConfigOptions {
  apiKey?: string
  model?: string
  temperature?: number
  maxTokens?: number
  topP?: number
  frequencyPenalty?: number
  presencePenalty?: number
}
export interface NodeLlmMessage {
  role: string
  content: string
}
export declare function runDag(filePath: string, resumeId?: string | undefined | null, resumeAnswer?: string | undefined | null, injectPayload?: any | undefined | null, includeExtraInfo?: boolean | undefined | null): Promise<any>
export declare function serveDag(filePath: string, host?: string | undefined | null, port?: number | undefined | null): Promise<void>
export declare class ColmenaLlm {
  constructor()
  call(messages: Array<NodeLlmMessage>, provider: string, options?: NodeLlmConfigOptions | undefined | null): Promise<string>
  healthCheck(provider: string): Promise<boolean>
  getProviders(): Array<string>
}
