/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function runDag(filePath: string, resumeId?: string | undefined | null, resumeAnswer?: string | undefined | null, injectPayload?: any | undefined | null, includeExtraInfo?: boolean | undefined | null, agentSessionId?: string | undefined | null): Promise<any>
/**
 * Like [`run_dag`] but accepts an already-serialized JSON string of the graph,
 * rather than a file path. Used by the TS facade to support in-memory graph objects.
 */
export declare function runDagFromJson(graphJson: string, resumeId?: string | undefined | null, resumeAnswer?: string | undefined | null, injectPayload?: any | undefined | null, includeExtraInfo?: boolean | undefined | null, agentSessionId?: string | undefined | null): Promise<any>
export declare function serveDag(filePath: string, host?: string | undefined | null, port?: number | undefined | null): Promise<void>
/** Validate a graph object; throws `DagError` if it is not a valid graph. */
export declare function validateGraph(graph: any): void
/**
 * Stream a DAG file's execution as SSE-mapped events. Returns a handle whose
 * `pull()` method yields the next `{ type: ... }` event, or `null` at completion.
 */
export declare function streamDag(filePath: string, resumeId?: string | undefined | null, resumeAnswer?: string | undefined | null, injectPayload?: any | undefined | null, includeExtraInfo?: boolean | undefined | null, agentSessionId?: string | undefined | null): Promise<DagStreamHandle>
/**
 * Like [`stream_dag`] but accepts an already-serialized JSON string of the graph,
 * rather than a file path. Used by the TS facade to support in-memory graph objects.
 */
export declare function streamDagFromJson(graphJson: string, resumeId?: string | undefined | null, resumeAnswer?: string | undefined | null, injectPayload?: any | undefined | null, includeExtraInfo?: boolean | undefined | null, agentSessionId?: string | undefined | null): Promise<DagStreamHandle>
export interface NodeLlmConfigOptions {
  apiKey?: string
  model?: string
  temperature?: number
  maxTokens?: number
  topP?: number
  frequencyPenalty?: number
  presencePenalty?: number
}
export interface NodeLlmMessage {
  role: string
  content: string
}
/**
 * Builds an inspection-only `HashMapNodeRegistry` with no live DB connections.
 * `PgPoolRegistry::new` is in-memory; pools are pinned lazily on first use,
 * which is fine because this registry is only used for introspection.
 */
export declare function defaultRegistry(): Registry
export declare class ColmenaLlm {
  constructor()
  call(messages: Array<NodeLlmMessage>, provider: string, options?: NodeLlmConfigOptions | undefined | null): Promise<string>
  stream(messages: Array<NodeLlmMessage>, provider: string, options?: NodeLlmConfigOptions | undefined | null): Promise<LlmStreamHandle>
  healthCheck(provider: string): Promise<boolean>
  getProviders(): Array<string>
}
/** Read-only handle to a `HashMapNodeRegistry`; inspection only, no DB. */
export declare class Registry {
  /** Return all registered node type names, sorted alphabetically. */
  nodeTypes(): Array<string>
  /**
   * Return the sub-tool catalog for a toolkit node, given its static config.
   * Throws if `node_type` is not a registered toolkit node.
   */
  toolkitCatalog(nodeType: string, config: any): any
}
/**
 * Async-iterator handle over an LLM text stream. Each `pull()` resolves to the
 * next chunk, or `null` when the stream is exhausted. The TS facade attaches
 * `[Symbol.asyncIterator]` so callers use `for await (const chunk of stream)`.
 */
export declare class LlmStreamHandle {
  /** Returns the next text chunk, or `null` when the stream is exhausted. */
  pull(): Promise<string | null>
}
/**
 * Async-iterator handle over a running DAG's SSE-mapped events. Each `pull()`
 * resolves to the next `{ type: ... }` event, or `null` when the graph finishes.
 */
export declare class DagStreamHandle {
  /** Returns the next DAG event, or `null` when the graph finishes. */
  pull(): Promise<any | null>
}
