/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function runDag(filePath: string, resumeId?: string | undefined | null, resumeAnswer?: string | undefined | null, injectPayload?: any | undefined | null, includeExtraInfo?: boolean | undefined | null, agentSessionId?: string | undefined | null): Promise<any>
/**
 * Like [`run_dag`] but accepts an already-serialized JSON string of the graph,
 * rather than a file path. Used by the TS facade to support in-memory graph objects.
 */
export declare function runDagFromJson(graphJson: string, resumeId?: string | undefined | null, resumeAnswer?: string | undefined | null, injectPayload?: any | undefined | null, includeExtraInfo?: boolean | undefined | null, agentSessionId?: string | undefined | null): Promise<any>
export declare function serveDag(filePath: string, host?: string | undefined | null, port?: number | undefined | null): Promise<void>
/** Validate a graph object; throws `DagError` if it is not a valid graph. */
export declare function validateGraph(graph: any): void
export interface NodeLlmConfigOptions {
  apiKey?: string
  model?: string
  temperature?: number
  maxTokens?: number
  topP?: number
  frequencyPenalty?: number
  presencePenalty?: number
}
export interface NodeLlmMessage {
  role: string
  content: string
}
export declare class ColmenaLlm {
  constructor()
  call(messages: Array<NodeLlmMessage>, provider: string, options?: NodeLlmConfigOptions | undefined | null): Promise<string>
  stream(messages: Array<NodeLlmMessage>, provider: string, options?: NodeLlmConfigOptions | undefined | null): Promise<LlmStreamHandle>
  healthCheck(provider: string): Promise<boolean>
  getProviders(): Array<string>
}
/**
 * Async-iterator handle over an LLM text stream. Each `pull()` resolves to the
 * next chunk, or `null` when the stream is exhausted. The TS facade attaches
 * `[Symbol.asyncIterator]` so callers use `for await (const chunk of stream)`.
 */
export declare class LlmStreamHandle {
  /** Returns the next text chunk, or `null` when the stream is exhausted. */
  pull(): Promise<string | null>
}
