/// Integration tests for the $DYNAMIC placeholder system in ToolConfiguration
/// This demonstrates how the LLM tool system handles fixed vs. dynamic parameters
/// using the declarative $DYNAMIC marker in fixed_config structures.

use colmena::dag_engine::domain::tool_configuration::{ToolConfiguration, DYNAMIC_PLACEHOLDER};
use colmena::dag_engine::infrastructure::dag_tool_executor::DagToolExecutor;
use colmena::dag_engine::application::ports::NodeRegistryPort;
use colmena::dag_engine::domain::node::{ExecutableNode, NodeInputs};
use colmena::llm::domain::{FunctionCall, ToolCall};
use async_trait::async_trait;
use serde_json::Value;
use std::collections::HashMap;
use std::sync::Arc;

/// Mock HTTP node that echoes inputs back (for testing)
struct MockHttpNode {
    name: String,
}

#[async_trait]
impl ExecutableNode for MockHttpNode {
    async fn execute(
        &self,
        inputs: &NodeInputs,
        _config: &Value,
        _state: &mut Value,
        _observer: Option<Arc<dyn colmena::dag_engine::domain::observer::ExecutionObserver>>,
    ) -> Result<Value, Box<dyn std::error::Error + Send + Sync>> {
        Ok(serde_json::to_value(inputs)?)
    }

    fn schema(&self) -> Value {
        serde_json::json!({
            "type": self.name,
            "inputs": {
                "base_url": "string",
                "endpoint": "string",
                "method": "string",
                "headers": "object",
                "body": "object"
            }
        })
    }
}

/// Mock registry for testing
struct MockHttpRegistry {
    nodes: HashMap<String, Arc<dyn ExecutableNode>>,
}

impl MockHttpRegistry {
    fn new() -> Self {
        let mut nodes = HashMap::new();
        nodes.insert(
            "http_request".to_string(),
            Arc::new(MockHttpNode {
                name: "http_request".to_string(),
            }) as Arc<dyn ExecutableNode>,
        );
        Self { nodes }
    }
}

impl NodeRegistryPort for MockHttpRegistry {
    fn get_node(&self, node_type: &str) -> Option<Arc<dyn ExecutableNode>> {
        self.nodes.get(node_type).cloned()
    }

    fn get_all_nodes(&self) -> HashMap<String, Arc<dyn ExecutableNode>> {
        self.nodes.clone()
    }
}

#[tokio::test]
async fn test_dynamic_placeholder_blog_post_creation() {
    // Simulates creating a blog post where:
    // - userId and author are always fixed
    // - title and content are generated by LLM
    let registry = Arc::new(MockHttpRegistry::new());
    let mut tool_configs = HashMap::new();

    // Build fixed_config with $DYNAMIC placeholders
    let mut body_fixed = serde_json::Map::new();
    body_fixed.insert("userId".to_string(), serde_json::json!(1));
    body_fixed.insert("author".to_string(), serde_json::json!("Fulanito"));
    body_fixed.insert("title".to_string(), serde_json::json!(DYNAMIC_PLACEHOLDER));
    body_fixed.insert("content".to_string(), serde_json::json!(DYNAMIC_PLACEHOLDER));

    let mut headers_fixed = serde_json::Map::new();
    headers_fixed.insert(
        "Content-Type".to_string(),
        serde_json::json!("application/json"),
    );

    let mut fixed_config = HashMap::new();
    fixed_config.insert("base_url".to_string(), serde_json::json!("https://jsonplaceholder.typicode.com"));
    fixed_config.insert("endpoint".to_string(), serde_json::json!("/posts"));
    fixed_config.insert("method".to_string(), serde_json::json!("POST"));
    fixed_config.insert("headers".to_string(), Value::Object(headers_fixed));
    fixed_config.insert("body".to_string(), Value::Object(body_fixed));

    tool_configs.insert(
        "create_blog_post".to_string(),
        ToolConfiguration {
            name: "create_blog_post".to_string(),
            description: "Create a new blog post with dynamic title and content".to_string(),
            node_type: "http_request".to_string(),
            fixed_config,
            exposed_inputs: None,
            parameters: None,
            mergeable_fields: None,
            field_mapping: None,
            node_schema: None,
        },
    );

    let executor = DagToolExecutor::new(registry, tool_configs);

    // Simulate LLM generating these values
    let llm_generated = r#"{
        "title": "The Future of AI in 2026",
        "content": "Artificial intelligence continues to revolutionize industries with unprecedented capabilities and opportunities."
    }"#;

    let tool_call = ToolCall::new(
        "call_blog_1".to_string(),
        FunctionCall::new("create_blog_post".to_string(), llm_generated.to_string()),
    );

    let result = executor.execute(&tool_call).await.unwrap();
    assert!(result.success, "Tool execution should succeed");

    let output: Value = serde_json::from_str(&result.output).unwrap();

    // Verify fixed values are present and unchanged
    assert_eq!(output["base_url"], "https://jsonplaceholder.typicode.com");
    assert_eq!(output["endpoint"], "/posts");
    assert_eq!(output["method"], "POST");
    assert_eq!(output["headers"]["Content-Type"], "application/json");
    assert_eq!(output["body"]["userId"], 1);
    assert_eq!(output["body"]["author"], "Fulanito");

    // Verify LLM-generated values are correctly placed
    assert_eq!(output["body"]["title"], "The Future of AI in 2026");
    assert_eq!(
        output["body"]["content"],
        "Artificial intelligence continues to revolutionize industries with unprecedented capabilities and opportunities."
    );
}

#[tokio::test]
async fn test_dynamic_placeholder_with_request_id() {
    // Simulates creating a post with a request ID in headers
    let registry = Arc::new(MockHttpRegistry::new());
    let mut tool_configs = HashMap::new();

    let mut body_fixed = serde_json::Map::new();
    body_fixed.insert("userId".to_string(), serde_json::json!(1));
    body_fixed.insert("author".to_string(), serde_json::json!("Fulanito"));
    body_fixed.insert("title".to_string(), serde_json::json!(DYNAMIC_PLACEHOLDER));

    let mut headers_fixed = serde_json::Map::new();
    headers_fixed.insert(
        "Content-Type".to_string(),
        serde_json::json!("application/json"),
    );
    headers_fixed.insert("X-Request-ID".to_string(), serde_json::json!(DYNAMIC_PLACEHOLDER));

    let mut fixed_config = HashMap::new();
    fixed_config.insert("base_url".to_string(), serde_json::json!("https://api.example.com"));
    fixed_config.insert("endpoint".to_string(), serde_json::json!("/posts"));
    fixed_config.insert("method".to_string(), serde_json::json!("POST"));
    fixed_config.insert("headers".to_string(), Value::Object(headers_fixed));
    fixed_config.insert("body".to_string(), Value::Object(body_fixed));

    tool_configs.insert(
        "create_post_with_id".to_string(),
        ToolConfiguration {
            name: "create_post_with_id".to_string(),
            description: "Create a post with request tracking".to_string(),
            node_type: "http_request".to_string(),
            fixed_config,
            exposed_inputs: None,
            parameters: None,
            mergeable_fields: None,
            field_mapping: None,
            node_schema: None,
        },
    );

    let executor = DagToolExecutor::new(registry, tool_configs);

    let tool_call = ToolCall::new(
        "call_blog_2".to_string(),
        FunctionCall::new(
            "create_post_with_id".to_string(),
            r#"{"title": "Web 3.0 Trends", "X-Request-ID": "req-abc-123-def"}"#.to_string(),
        ),
    );

    let result = executor.execute(&tool_call).await.unwrap();
    assert!(result.success);

    let output: Value = serde_json::from_str(&result.output).unwrap();

    // Verify headers merge correctly
    assert_eq!(output["headers"]["Content-Type"], "application/json");
    assert_eq!(output["headers"]["X-Request-ID"], "req-abc-123-def");

    // Verify body has both fixed and dynamic
    assert_eq!(output["body"]["userId"], 1);
    assert_eq!(output["body"]["author"], "Fulanito");
    assert_eq!(output["body"]["title"], "Web 3.0 Trends");
}

#[tokio::test]
async fn test_dynamic_tool_definition_generation() {
    // Verify that tool definitions are correctly generated from $DYNAMIC placeholders
    let registry = Arc::new(MockHttpRegistry::new());
    let mut tool_configs = HashMap::new();

    let mut body_fixed = serde_json::Map::new();
    body_fixed.insert("userId".to_string(), serde_json::json!(1));
    body_fixed.insert("title".to_string(), serde_json::json!(DYNAMIC_PLACEHOLDER));
    body_fixed.insert("content".to_string(), serde_json::json!(DYNAMIC_PLACEHOLDER));

    let mut fixed_config = HashMap::new();
    fixed_config.insert("base_url".to_string(), serde_json::json!("https://api.example.com"));
    fixed_config.insert("endpoint".to_string(), serde_json::json!("/posts"));
    fixed_config.insert("method".to_string(), serde_json::json!("POST"));
    fixed_config.insert("body".to_string(), Value::Object(body_fixed));

    tool_configs.insert(
        "create_post".to_string(),
        ToolConfiguration {
            name: "create_post".to_string(),
            description: "Create a new post".to_string(),
            node_type: "http_request".to_string(),
            fixed_config,
            exposed_inputs: None,
            parameters: None,
            mergeable_fields: None,
            field_mapping: None,
            node_schema: None,
        },
    );

    let executor = DagToolExecutor::new(registry, tool_configs);
    let tools = executor.available_tools().await;

    let tool_def = tools
        .iter()
        .find(|t| t.name == "create_post")
        .expect("create_post tool should be available");

    // Verify that only the $DYNAMIC fields are exposed
    assert_eq!(tool_def.parameters.properties.len(), 2);
    assert!(tool_def.parameters.properties.contains_key("title"));
    assert!(tool_def.parameters.properties.contains_key("content"));

    // userId should NOT be in properties (it's fixed)
    assert!(!tool_def.parameters.properties.contains_key("userId"));
    assert!(!tool_def.parameters.properties.contains_key("base_url"));
    assert!(!tool_def.parameters.properties.contains_key("endpoint"));

    // Both should be required
    assert_eq!(tool_def.parameters.required.len(), 2);
    assert!(tool_def.parameters.required.contains(&"title".to_string()));
    assert!(tool_def.parameters.required.contains(&"content".to_string()));
}

#[tokio::test]
async fn test_dynamic_vs_fixed_security() {
    // Verify that LLM cannot override fixed values
    // Even if LLM tries to provide "author", it's ignored because it's fixed
    let registry = Arc::new(MockHttpRegistry::new());
    let mut tool_configs = HashMap::new();

    let mut body_fixed = serde_json::Map::new();
    body_fixed.insert("userId".to_string(), serde_json::json!(1));
    body_fixed.insert("author".to_string(), serde_json::json!("Fulanito"));
    body_fixed.insert("title".to_string(), serde_json::json!(DYNAMIC_PLACEHOLDER));

    let mut fixed_config = HashMap::new();
    fixed_config.insert("base_url".to_string(), serde_json::json!("https://api.example.com"));
    fixed_config.insert("endpoint".to_string(), serde_json::json!("/posts"));
    fixed_config.insert("method".to_string(), serde_json::json!("POST"));
    fixed_config.insert("body".to_string(), Value::Object(body_fixed));

    tool_configs.insert(
        "secure_post".to_string(),
        ToolConfiguration {
            name: "secure_post".to_string(),
            description: "Create a post securely".to_string(),
            node_type: "http_request".to_string(),
            fixed_config,
            exposed_inputs: None,
            parameters: None,
            mergeable_fields: None,
            field_mapping: None,
            node_schema: None,
        },
    );

    let executor = DagToolExecutor::new(registry, tool_configs);

    // Try to provide "author" in LLM arguments (this is fixed, not dynamic)
    let tool_call = ToolCall::new(
        "call_secure_1".to_string(),
        FunctionCall::new(
            "secure_post".to_string(),
            r#"{"title": "Test", "author": "Hacker"}"#.to_string(),
        ),
    );

    let result = executor.execute(&tool_call).await.unwrap();
    assert!(result.success);

    let output: Value = serde_json::from_str(&result.output).unwrap();

    // author should ALWAYS be "Fulanito", never "Hacker"
    // Because author is fixed, not $DYNAMIC
    assert_eq!(output["body"]["author"], "Fulanito");
    assert_eq!(output["body"]["title"], "Test");

    // Also verify that userId (fixed, non-$DYNAMIC) is never overrideable
    let tool_call2 = ToolCall::new(
        "call_secure_2".to_string(),
        FunctionCall::new(
            "secure_post".to_string(),
            r#"{"title": "Another", "userId": 999}"#.to_string(),
        ),
    );

    let result2 = executor.execute(&tool_call2).await.unwrap();
    assert!(result2.success);

    let output2: Value = serde_json::from_str(&result2.output).unwrap();
    assert_eq!(output2["body"]["userId"], 1, "userId should remain fixed at 1");
}

#[tokio::test]
async fn test_dynamic_with_multiple_containers() {
    // Test $DYNAMIC placeholders across different container fields (body, headers, query_params, etc.)
    let registry = Arc::new(MockHttpRegistry::new());
    let mut tool_configs = HashMap::new();

    let mut body_fixed = serde_json::Map::new();
    body_fixed.insert("action".to_string(), serde_json::json!("create"));
    body_fixed.insert("data".to_string(), serde_json::json!(DYNAMIC_PLACEHOLDER));

    let mut headers_fixed = serde_json::Map::new();
    headers_fixed.insert("Authorization".to_string(), serde_json::json!("Bearer secret123"));
    headers_fixed.insert("X-Custom".to_string(), serde_json::json!(DYNAMIC_PLACEHOLDER));

    let mut fixed_config = HashMap::new();
    fixed_config.insert("base_url".to_string(), serde_json::json!("https://api.example.com"));
    fixed_config.insert("endpoint".to_string(), serde_json::json!("/api/items"));
    fixed_config.insert("method".to_string(), serde_json::json!("POST"));
    fixed_config.insert("body".to_string(), Value::Object(body_fixed));
    fixed_config.insert("headers".to_string(), Value::Object(headers_fixed));

    tool_configs.insert(
        "complex_call".to_string(),
        ToolConfiguration {
            name: "complex_call".to_string(),
            description: "Complex API call with dynamic params across containers".to_string(),
            node_type: "http_request".to_string(),
            fixed_config,
            exposed_inputs: None,
            parameters: None,
            mergeable_fields: None,
            field_mapping: None,
            node_schema: None,
        },
    );

    let executor = DagToolExecutor::new(registry, tool_configs);

    let tool_call = ToolCall::new(
        "call_complex_1".to_string(),
        FunctionCall::new(
            "complex_call".to_string(),
            r#"{"data": {"items": [1, 2, 3]}, "X-Custom": "custom-value"}"#.to_string(),
        ),
    );

    let result = executor.execute(&tool_call).await.unwrap();
    assert!(result.success);

    let output: Value = serde_json::from_str(&result.output).unwrap();

    // Verify fixed values in body
    assert_eq!(output["body"]["action"], "create");

    // Verify dynamic value in body
    assert_eq!(output["body"]["data"]["items"][0], 1);

    // Verify fixed headers are preserved
    assert_eq!(output["headers"]["Authorization"], "Bearer secret123");

    // Verify dynamic header value is placed correctly
    assert_eq!(output["headers"]["X-Custom"], "custom-value");

    // Verify immutable fields
    assert_eq!(output["base_url"], "https://api.example.com");
    assert_eq!(output["endpoint"], "/api/items");
    assert_eq!(output["method"], "POST");
}

/// Test 1: node_schema generates correct tool definition
#[tokio::test]
async fn test_node_schema_tool_definition() {
    use colmena::dag_engine::domain::tool_configuration::{NodeSchema, NodeSchemaField};
    use serde_json::json;

    let mut schema = NodeSchema::new();
    schema.insert(
        "base_url".to_string(),
        NodeSchemaField {
            field_type: "string".to_string(),
            fixed: Some(json!("https://api.example.com")),
            required: None,
            description: None,
            pattern: None,
            properties: None,
        },
    );

    // query_params container with fixed max and required originLocationCode
    let mut query_params_props = std::collections::HashMap::new();
    query_params_props.insert(
        "max".to_string(),
        NodeSchemaField {
            field_type: "string".to_string(),
            fixed: Some(json!("5")),
            required: None,
            description: None,
            pattern: None,
            properties: None,
        },
    );
    query_params_props.insert(
        "originLocationCode".to_string(),
        NodeSchemaField {
            field_type: "string".to_string(),
            fixed: None,
            required: Some(true),
            description: Some("Origin IATA code".to_string()),
            pattern: None,
            properties: None,
        },
    );
    query_params_props.insert(
        "children".to_string(),
        NodeSchemaField {
            field_type: "string".to_string(),
            fixed: None,
            required: Some(false),
            description: Some("Optional children count".to_string()),
            pattern: None,
            properties: None,
        },
    );

    schema.insert(
        "query_params".to_string(),
        NodeSchemaField {
            field_type: "object".to_string(),
            fixed: None,
            required: None,
            description: None,
            pattern: None,
            properties: Some(query_params_props),
        },
    );

    let mut tool_configs = std::collections::HashMap::new();
    tool_configs.insert(
        "search_flights".to_string(),
        ToolConfiguration {
            name: "search_flights".to_string(),
            description: "Search for flights".to_string(),
            node_type: "mock_tool".to_string(),
            fixed_config: std::collections::HashMap::new(),
            exposed_inputs: None,
            parameters: None,
            mergeable_fields: None,
            field_mapping: None,
            node_schema: Some(schema),
        },
    );

    let registry = MockRegistry::new();
    let executor = DagToolExecutor::new(std::sync::Arc::new(registry), tool_configs);

    let tools = executor.available_tools().await;
    let search_flights = tools.iter().find(|t| t.name == "search_flights").unwrap();

    // Verify fixed fields are NOT in properties
    assert!(!search_flights.parameters.properties.contains_key("base_url"));
    assert!(!search_flights.parameters.properties.contains_key("max"));

    // Verify required params are in required array
    assert!(search_flights.parameters.required.contains(&"originLocationCode".to_string()));
    assert!(!search_flights.parameters.required.contains(&"children".to_string()));

    // Verify optional param is in properties but not required
    assert!(search_flights.parameters.properties.contains_key("children"));
    assert!(!search_flights.parameters.required.contains(&"children".to_string()));
}

/// Test 2: node_schema merges LLM args correctly into containers
#[tokio::test]
async fn test_node_schema_execute_merges_container() {
    use colmena::dag_engine::domain::tool_configuration::{NodeSchema, NodeSchemaField};
    use serde_json::json;

    let mut query_params_props = std::collections::HashMap::new();
    query_params_props.insert(
        "max".to_string(),
        NodeSchemaField {
            field_type: "string".to_string(),
            fixed: Some(json!("5")),
            required: None,
            description: None,
            pattern: None,
            properties: None,
        },
    );
    query_params_props.insert(
        "originLocationCode".to_string(),
        NodeSchemaField {
            field_type: "string".to_string(),
            fixed: None,
            required: Some(true),
            description: None,
            pattern: None,
            properties: None,
        },
    );

    let mut schema = NodeSchema::new();
    schema.insert(
        "query_params".to_string(),
        NodeSchemaField {
            field_type: "object".to_string(),
            fixed: None,
            required: None,
            description: None,
            pattern: None,
            properties: Some(query_params_props),
        },
    );

    let mut tool_configs = std::collections::HashMap::new();
    tool_configs.insert(
        "test_tool".to_string(),
        ToolConfiguration {
            name: "test_tool".to_string(),
            description: "Test".to_string(),
            node_type: "mock_tool".to_string(),
            fixed_config: std::collections::HashMap::new(),
            exposed_inputs: None,
            parameters: None,
            mergeable_fields: None,
            field_mapping: None,
            node_schema: Some(schema),
        },
    );

    let registry = MockRegistry::new();
    let executor = DagToolExecutor::new(std::sync::Arc::new(registry), tool_configs);

    let tool_call = ToolCall::new(
        "call_1".to_string(),
        FunctionCall {
            name: "test_tool".to_string(),
            arguments: r#"{"originLocationCode": "MAD"}"#.to_string(),
        },
    );

    let result = executor.execute(&tool_call).await.unwrap();
    let output: serde_json::Value = serde_json::from_str(&result.output).unwrap();

    // Verify fixed max=5 is preserved
    assert_eq!(output["query_params"]["max"], "5");

    // Verify LLM-provided originLocationCode is in query_params
    assert_eq!(output["query_params"]["originLocationCode"], "MAD");
}

/// Test 3: node_schema fixed values are immutable
#[tokio::test]
async fn test_node_schema_fixed_is_immutable() {
    use colmena::dag_engine::domain::tool_configuration::{NodeSchema, NodeSchemaField};
    use serde_json::json;

    let mut query_params_props = std::collections::HashMap::new();
    query_params_props.insert(
        "max".to_string(),
        NodeSchemaField {
            field_type: "string".to_string(),
            fixed: Some(json!("5")),
            required: None,
            description: None,
            pattern: None,
            properties: None,
        },
    );

    let mut schema = NodeSchema::new();
    schema.insert(
        "query_params".to_string(),
        NodeSchemaField {
            field_type: "object".to_string(),
            fixed: None,
            required: None,
            description: None,
            pattern: None,
            properties: Some(query_params_props),
        },
    );

    let mut tool_configs = std::collections::HashMap::new();
    tool_configs.insert(
        "test_tool".to_string(),
        ToolConfiguration {
            name: "test_tool".to_string(),
            description: "Test".to_string(),
            node_type: "mock_tool".to_string(),
            fixed_config: std::collections::HashMap::new(),
            exposed_inputs: None,
            parameters: None,
            mergeable_fields: None,
            field_mapping: None,
            node_schema: Some(schema),
        },
    );

    let registry = MockRegistry::new();
    let executor = DagToolExecutor::new(std::sync::Arc::new(registry), tool_configs);

    // LLM tries to send max=100
    let tool_call = ToolCall::new(
        "call_1".to_string(),
        FunctionCall {
            name: "test_tool".to_string(),
            arguments: r#"{"max": "100"}"#.to_string(),
        },
    );

    let result = executor.execute(&tool_call).await.unwrap();
    let output: serde_json::Value = serde_json::from_str(&result.output).unwrap();

    // Verify max is still "5", not "100" (LLM cannot override fixed values)
    assert_eq!(output["query_params"]["max"], "5");
}

/// Test 4: node_schema takes priority over $DYNAMIC
#[tokio::test]
async fn test_node_schema_priority_over_dynamic() {
    use colmena::dag_engine::domain::tool_configuration::{NodeSchema, NodeSchemaField};
    use serde_json::json;

    let mut schema = NodeSchema::new();
    schema.insert(
        "originLocationCode".to_string(),
        NodeSchemaField {
            field_type: "string".to_string(),
            fixed: None,
            required: Some(true),
            description: None,
            pattern: None,
            properties: None,
        },
    );

    let mut fixed_config = std::collections::HashMap::new();
    fixed_config.insert("unused_field".to_string(), json!("$DYNAMIC"));

    let mut tool_configs = std::collections::HashMap::new();
    tool_configs.insert(
        "test_tool".to_string(),
        ToolConfiguration {
            name: "test_tool".to_string(),
            description: "Test".to_string(),
            node_type: "mock_tool".to_string(),
            fixed_config,
            exposed_inputs: None,
            parameters: None,
            mergeable_fields: None,
            field_mapping: None,
            node_schema: Some(schema),
        },
    );

    let registry = MockRegistry::new();
    let executor = DagToolExecutor::new(std::sync::Arc::new(registry), tool_configs);

    let tools = executor.available_tools().await;
    let test_tool = tools.iter().find(|t| t.name == "test_tool").unwrap();

    // Verify node_schema is used (originLocationCode is required)
    assert!(test_tool.parameters.required.contains(&"originLocationCode".to_string()));

    // Verify $DYNAMIC is NOT processed (unused_field should not be in properties)
    assert!(!test_tool.parameters.properties.contains_key("unused_field"));
}
