//! Plan A: render the attachment catalog block that gets prepended to the
//! LLM node's system message. Lists every attachment registered for the
//! current agent_session_id with its document_id, metadata, and usage hint.

use crate::llm::domain::attachments::ConversationAttachment;

pub fn render_catalog(attachments: &[ConversationAttachment]) -> Option<String> {
    if attachments.is_empty() {
        return None;
    }

    let mut out = String::from("Documents available in this session:\n\n");
    for a in attachments {
        out.push_str(&format!("[{}]\n", a.document_id));
        out.push_str(&format!(
            "  filename: {} · {} · {}\n",
            a.filename,
            a.mime_type,
            human_size(a.size_bytes),
        ));
        if let Some(desc) = a.description.as_deref().filter(|s| !s.trim().is_empty()) {
            out.push_str(&format!("  description: {}\n", desc.trim()));
        }
        if let Some(origin) = a.origin.as_deref() {
            out.push_str(&format!("  origin: {}\n", humanize_origin(origin)));
        }
        out.push_str(&format!(
            "  created: {}\n",
            a.registered_at.format("%Y-%m-%d %H:%M UTC")
        ));
        out.push_str(&format!(
            "  usage: load_attachment(\"{}\") to read · \"$attachment:{}\" to forward\n\n",
            a.document_id, a.document_id
        ));
    }
    Some(out.trim_end().to_string())
}

fn humanize_origin(s: &str) -> String {
    if let Some(rest) = s.strip_prefix("generated_by:") {
        format!("generated by {}", rest)
    } else if s == "user_upload" {
        "uploaded by user".to_string()
    } else {
        s.to_string()
    }
}

fn human_size(bytes: Option<u64>) -> String {
    let Some(b) = bytes else {
        return "? bytes".to_string();
    };
    const KB: u64 = 1024;
    const MB: u64 = KB * 1024;
    if b >= MB {
        format!("{:.1} MB", b as f64 / MB as f64)
    } else if b >= KB {
        format!("{:.1} KB", b as f64 / KB as f64)
    } else {
        format!("{} B", b)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::llm::domain::attachments::{AttachmentSource, ConversationAttachment};
    use crate::llm::domain::ProviderKind;
    use chrono::Utc;

    fn mk(did: &str, origin: &str) -> ConversationAttachment {
        ConversationAttachment {
            agent_session_id: "a".to_string(),
            document_id: did.to_string(),
            provider: ProviderKind::OpenAi,
            provider_file_id: "pf".to_string(),
            mime_type: "application/pdf".to_string(),
            filename: "x.pdf".to_string(),
            size_bytes: Some(1024 * 1024),
            label: None,
            description: Some("a summary".to_string()),
            source: AttachmentSource::Inline,
            registered_at: Utc::now(),
            refreshed_at: Utc::now(),
            storage_key: Some("sk".to_string()),
            origin: Some(origin.to_string()),
            last_used_at: None,
        }
    }

    #[test]
    fn empty_list_returns_none() {
        assert!(render_catalog(&[]).is_none());
    }

    #[test]
    fn single_doc_renders_full_block() {
        let out = render_catalog(&[mk("doc-1", "user_upload")]).unwrap();
        assert!(out.starts_with("Documents available in this session:"));
        assert!(out.contains("[doc-1]"));
        assert!(out.contains("filename: x.pdf · application/pdf · 1.0 MB"));
        assert!(out.contains("description: a summary"));
        assert!(out.contains("origin: uploaded by user"));
        assert!(
            out.contains("load_attachment(\"doc-1\") to read · \"$attachment:doc-1\" to forward")
        );
    }

    #[test]
    fn generated_origin_humanizes_correctly() {
        let out = render_catalog(&[mk("img-1", "generated_by:image_generation")]).unwrap();
        assert!(out.contains("origin: generated by image_generation"));
    }
}
