use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;

/// Marker used in fixed_config values to indicate a field should be generated by the LLM
pub const DYNAMIC_PLACEHOLDER: &str = "$DYNAMIC";

/// Configuration for exposing a node as a tool
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolConfiguration {
    /// Name of the tool (shown to LLM)
    pub name: String,

    /// Human-readable description for the LLM
    pub description: String,

    /// Node type to execute
    pub node_type: String,

    /// Fixed configuration values (not exposed to LLM)
    pub fixed_config: HashMap<String, Value>,

    /// Which input parameters to expose to the LLM
    /// If None, expose all inputs not in fixed_config
    pub exposed_inputs: Option<Vec<String>>,

    /// Optional JSON Schema for parameters to override node schema
    pub parameters: Option<Value>,

    /// Fields where fixed + dynamic values should be merged (not overridden).
    /// Example: ["headers", "query_params", "body"]
    /// When merging a field listed here, the fixed object is the base
    /// and the dynamic (LLM-provided) object overlays it.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub mergeable_fields: Option<Vec<String>>,

    /// Maps each LLM parameter to its destination container field.
    /// The parameter value is moved into that container under its own key.
    /// Example: {"title" → "body", "x_request_id" → "headers"}
    /// Parameters not listed in this map are kept at the top level.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub field_mapping: Option<HashMap<String, String>>,
}
