//! `insert_after_text`, `insert_before_text`, `insert_between` use cases.
//!
//! All three are content-addressed: the agent specifies anchor text(s);
//! the dispatcher locates them in the snapshot, computes a UTF-16
//! insertion index, converts `new_markdown` via `markdown_to_docs_ops`,
//! and POSTs one batchUpdate.
//!
//! v1 limitation: markdown containing table syntax (`|...|...|`) is
//! rejected with `InvalidArgs`. The converter's table emission is not
//! API-shaped in v1; rewriting requires a snapshot round-trip we defer
//! to v1.1. See `markdown_to_docs_ops.rs` source comments for details.

use crate::dag_engine::infrastructure::nodes::llm_synthetic_tools::markdown_to_docs_ops::{
    markdown_to_requests, InsertionPoint,
};
use crate::gdocs::application::co_edit_guard::{run_guard, GuardContext};
use crate::gdocs::domain::{
    ChangeKind, ChangeRecord, DocsError, DocumentId, DocumentSnapshot, EditResult, OutlineEntry,
    ParagraphSnapshot, Scope, TabId,
};

#[derive(Debug, Clone)]
pub struct InsertAfterTextInput {
    pub anchor: String,
    pub new_markdown: String,
    pub occurrence: Option<u32>,
}

#[derive(Debug, Clone)]
pub struct InsertBeforeTextInput {
    pub anchor: String,
    pub new_markdown: String,
    pub occurrence: Option<u32>,
}

#[derive(Debug, Clone)]
pub struct InsertBetweenInput {
    /// Heading like `"## Section A"`. Required.
    pub after_heading: String,
    /// Heading like `"## Section B"`. `None` → EOF.
    pub before_heading: Option<String>,
    pub new_markdown: String,
}

#[derive(Debug, Clone)]
pub struct InsertImageAfterTextInput {
    /// Anchor text to locate; the image is inserted right after the match.
    pub anchor: String,
    /// Publicly-accessible image URL. Google fetches it server-side, so it
    /// must be reachable without auth (PNG/JPEG/GIF, ≤50 MB, ≤2000 chars).
    pub image_url: String,
    pub occurrence: Option<u32>,
    /// Optional render size in points (PT). When both are omitted Docs uses
    /// the image's native size.
    pub width_pt: Option<f64>,
    pub height_pt: Option<f64>,
}

/// Insert after the (occurrence-th) match of `anchor` in the doc.
pub async fn run_after_text(
    ctx: &GuardContext<'_>,
    doc_id: &DocumentId,
    input: InsertAfterTextInput,
) -> Result<EditResult, DocsError> {
    reject_table_markdown(&input.new_markdown)?;
    let guard = run_guard(ctx, doc_id, &Scope::All).await?;
    let snap = &guard.snapshot;
    let (para_n, byte_off, byte_len, tab_id) = find_anchor(snap, &input.anchor, input.occurrence)?;
    let p = lookup_para(snap, para_n);
    // Insert AFTER the match: byte_off + byte_len within the paragraph.
    let after_byte = byte_off + byte_len;
    let prefix_utf16 = utf16_len(&p.text[..after_byte]);
    let index = p.start_index + prefix_utf16;

    let conversion = markdown_to_requests(
        &input.new_markdown,
        InsertionPoint::Index {
            index,
            tab_id: tab_id.clone(),
        },
    );

    apply_and_finalize(
        ctx,
        doc_id,
        snap,
        conversion.requests,
        ChangeKind::Insert,
        para_n,
        &input.new_markdown,
        tab_id,
        conversion.lossy,
        guard.soft_warnings,
    )
    .await
}

/// Insert an inline image AFTER the (occurrence-th) match of `anchor`.
///
/// Path (i) of the image-insert design: `image_url` must be a publicly
/// accessible URL (Google fetches the bytes server-side). Attachment-sourced
/// images (signed-URL or generated bytes uploaded to Drive) are deferred to
/// v1.1 — see BACKLOG "Subsystem G v1.1 → gdocs_insert_image_after_text".
///
/// Reuses the same anchor-resolution + finalize machinery as `run_after_text`;
/// only the emitted `Request` differs (`insertInlineImage` instead of
/// `insertText`).
pub async fn run_insert_image_after_text(
    ctx: &GuardContext<'_>,
    doc_id: &DocumentId,
    input: InsertImageAfterTextInput,
) -> Result<EditResult, DocsError> {
    validate_image_url(&input.image_url)?;
    let guard = run_guard(ctx, doc_id, &Scope::All).await?;
    let snap = &guard.snapshot;
    let (para_n, byte_off, byte_len, tab_id) = find_anchor(snap, &input.anchor, input.occurrence)?;
    let p = lookup_para(snap, para_n);
    // Insert AFTER the match: byte_off + byte_len within the paragraph.
    let after_byte = byte_off + byte_len;
    let prefix_utf16 = utf16_len(&p.text[..after_byte]);
    let index = p.start_index + prefix_utf16;

    let request = build_insert_image_request(
        index,
        tab_id.as_ref(),
        &input.image_url,
        input.width_pt,
        input.height_pt,
    );

    apply_and_finalize(
        ctx,
        doc_id,
        snap,
        vec![request],
        ChangeKind::Insert,
        para_n,
        &format!("[image] {}", input.image_url),
        tab_id,
        vec![], // image insert is never lossy
        guard.soft_warnings,
    )
    .await
}

/// Map an image mime to a Drive filename extension. Returns `None` for
/// non-image / unsupported mimes (Docs only accepts PNG/JPEG/GIF).
pub(crate) fn image_ext_for_mime(mime: &str) -> Option<&'static str> {
    match mime {
        "image/png" => Some("png"),
        "image/jpeg" | "image/jpg" => Some("jpg"),
        "image/gif" => Some("gif"),
        _ => None,
    }
}

/// Short non-secret token for temp filenames. Uses the process clock; collision
/// is harmless (filenames need not be unique). Avoids adding an RNG dep.
fn short_token() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let n = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    format!("{:x}", n & 0xffff_ffff)
}

/// Insert an image from raw bytes (Approach A): upload to Drive → make public
/// → insert via the lh3 content URL → delete the temp Drive file. Returns the
/// `EditResult` plus any soft warnings (e.g. temp-file cleanup failed — the
/// insert still succeeded). Transactional: if a step AFTER the upload fails,
/// the temp Drive file is deleted before returning the error.
pub async fn run_insert_image_from_bytes(
    ctx: &GuardContext<'_>,
    doc_id: &DocumentId,
    input: InsertImageAfterTextInput,
    bytes: Vec<u8>,
    mime: &str,
) -> Result<(EditResult, Vec<String>), DocsError> {
    let ext = image_ext_for_mime(mime).ok_or_else(|| {
        DocsError::InvalidArgs(format!(
            "attachment mime '{mime}' is not a supported image (need image/png, image/jpeg, or image/gif)"
        ))
    })?;
    let filename = format!("colmena-tmp-img-{}.{ext}", short_token());
    let file_id = ctx
        .client
        .upload_image_to_drive(bytes, mime, &filename)
        .await?;

    // From here on, clean up the uploaded file if anything fails.
    if let Err(e) = ctx.client.set_anyone_reader(&file_id).await {
        let _ = ctx.client.delete_drive_file(&file_id).await;
        return Err(e);
    }
    let uri = format!("https://lh3.googleusercontent.com/d/{file_id}");
    let image_input = InsertImageAfterTextInput {
        anchor: input.anchor,
        image_url: uri,
        occurrence: input.occurrence,
        width_pt: input.width_pt,
        height_pt: input.height_pt,
    };
    let result = match run_insert_image_after_text(ctx, doc_id, image_input).await {
        Ok(r) => r,
        Err(e) => {
            let _ = ctx.client.delete_drive_file(&file_id).await;
            return Err(e);
        }
    };
    // Insert succeeded — Google has copied the image. Best-effort cleanup.
    let mut warnings = Vec::new();
    if let Err(e) = ctx.client.delete_drive_file(&file_id).await {
        warnings.push(format!(
            "image inserted OK, but the temp Drive file '{file_id}' could not be deleted: {e}"
        ));
    }
    Ok((result, warnings))
}

/// Insert before the (occurrence-th) match of `anchor`.
pub async fn run_before_text(
    ctx: &GuardContext<'_>,
    doc_id: &DocumentId,
    input: InsertBeforeTextInput,
) -> Result<EditResult, DocsError> {
    reject_table_markdown(&input.new_markdown)?;
    let guard = run_guard(ctx, doc_id, &Scope::All).await?;
    let snap = &guard.snapshot;
    let (para_n, byte_off, _byte_len, tab_id) = find_anchor(snap, &input.anchor, input.occurrence)?;
    let p = lookup_para(snap, para_n);
    let prefix_utf16 = utf16_len(&p.text[..byte_off]);
    let index = p.start_index + prefix_utf16;

    let conversion = markdown_to_requests(
        &input.new_markdown,
        InsertionPoint::Index {
            index,
            tab_id: tab_id.clone(),
        },
    );

    apply_and_finalize(
        ctx,
        doc_id,
        snap,
        conversion.requests,
        ChangeKind::Insert,
        para_n,
        &input.new_markdown,
        tab_id,
        conversion.lossy,
        guard.soft_warnings,
    )
    .await
}

/// Insert between two headings. Uses scope_resolver's BetweenHeadings
/// for paragraph-range resolution; the insertion index is the
/// `start_index` of the first paragraph after the `after_heading`
/// (existing content gets pushed down).
pub async fn run_between(
    ctx: &GuardContext<'_>,
    doc_id: &DocumentId,
    input: InsertBetweenInput,
) -> Result<EditResult, DocsError> {
    reject_table_markdown(&input.new_markdown)?;
    let scope = Scope::BetweenHeadings {
        after: input.after_heading.clone(),
        before: input.before_heading.clone(),
    };
    let guard = run_guard(ctx, doc_id, &scope).await?;
    let snap = &guard.snapshot;
    // Use the resolved scope's paragraph_start (which is the FIRST
    // paragraph AFTER the `after` heading). We insert at its
    // start_index, pushing existing content down.
    let n = guard.resolved_scope.paragraph_start;
    let p = lookup_para_or_eof(snap, n);
    let index = p.start_index;
    let tab_id = guard.resolved_scope.tab_id.clone();

    let conversion = markdown_to_requests(
        &input.new_markdown,
        InsertionPoint::Index {
            index,
            tab_id: tab_id.clone(),
        },
    );

    apply_and_finalize(
        ctx,
        doc_id,
        snap,
        conversion.requests,
        ChangeKind::Insert,
        n,
        &input.new_markdown,
        tab_id,
        conversion.lossy,
        guard.soft_warnings,
    )
    .await
}

// ── Helpers ────────────────────────────────────────────────────────

/// Pre-scan markdown for table syntax; reject with a clear v1 message.
pub(crate) fn reject_table_markdown(md: &str) -> Result<(), DocsError> {
    // A CommonMark table requires a separator line of the form
    // `|---|---|` (with optional colons for alignment). The simplest
    // reliable check is matching that separator line — bash pipes and
    // text containing literal `|` won't trip this.
    let re = regex::Regex::new(r"(?m)^\s*\|?\s*:?-{3,}:?(\s*\|\s*:?-{3,}:?)+\s*\|?\s*$")
        .expect("static regex");
    if re.is_match(md) {
        return Err(DocsError::InvalidArgs(
            "v1 limitation: markdown tables are not supported in insert/replace use cases. \
             Use the dedicated `gdocs_insert_table` tool in v1.1, or emit the table content \
             as a regular paragraph list for now."
                .to_string(),
        ));
    }
    Ok(())
}

/// Validate the image URL before hitting the API: it must be a public
/// http(s) URL within the Docs API's 2000-char URI limit. We do NOT fetch
/// it — Google does that server-side. Attachment ids are rejected here with
/// a pointer to the (deferred) v1.1 path.
fn validate_image_url(url: &str) -> Result<(), DocsError> {
    let u = url.trim();
    if u.is_empty() {
        return Err(DocsError::InvalidArgs(
            "image_url must not be empty".to_string(),
        ));
    }
    if !(u.starts_with("http://") || u.starts_with("https://")) {
        return Err(DocsError::InvalidArgs(
            "image_url must be a public http(s) URL — Google fetches the image \
             server-side, so it has to be reachable without auth. Inserting from \
             an attachment_id (signed-URL or generated image) is not supported yet \
             (Subsystem G v1.1)."
                .to_string(),
        ));
    }
    // Docs API caps the inline-image URI at 2000 characters.
    if u.chars().count() > 2000 {
        return Err(DocsError::InvalidArgs(
            "image_url exceeds the Docs API 2000-character URI limit".to_string(),
        ));
    }
    Ok(())
}

/// Build a single `insertInlineImage` batchUpdate request. `objectSize` is
/// emitted only when at least one dimension is provided; otherwise Docs uses
/// the image's native size. The location shape mirrors `markdown_to_docs_ops::loc`.
fn build_insert_image_request(
    index: u32,
    tab_id: Option<&TabId>,
    uri: &str,
    width_pt: Option<f64>,
    height_pt: Option<f64>,
) -> serde_json::Value {
    let mut location = serde_json::Map::new();
    location.insert("index".to_string(), serde_json::json!(index));
    if let Some(t) = tab_id {
        location.insert("tabId".to_string(), serde_json::json!(t.0));
    }
    let mut img = serde_json::Map::new();
    img.insert("location".to_string(), serde_json::Value::Object(location));
    img.insert("uri".to_string(), serde_json::json!(uri.trim()));
    if width_pt.is_some() || height_pt.is_some() {
        let mut size = serde_json::Map::new();
        if let Some(w) = width_pt {
            size.insert(
                "width".to_string(),
                serde_json::json!({"magnitude": w, "unit": "PT"}),
            );
        }
        if let Some(h) = height_pt {
            size.insert(
                "height".to_string(),
                serde_json::json!({"magnitude": h, "unit": "PT"}),
            );
        }
        img.insert("objectSize".to_string(), serde_json::Value::Object(size));
    }
    serde_json::json!({ "insertInlineImage": serde_json::Value::Object(img) })
}

/// Locate the (occurrence-th) match of `anchor` in the doc. Returns
/// `(paragraph_n, byte_off_in_paragraph, byte_len, tab_id)`.
fn find_anchor(
    snap: &DocumentSnapshot,
    anchor: &str,
    occurrence: Option<u32>,
) -> Result<(u32, usize, usize, Option<TabId>), DocsError> {
    if anchor.is_empty() {
        return Err(DocsError::InvalidArgs(
            "anchor text must not be empty".to_string(),
        ));
    }
    let mut hits: Vec<(u32, usize, usize, Option<TabId>)> = Vec::new();
    for tab in &snap.tabs {
        for p in &tab.paragraphs {
            let mut start = 0;
            while let Some(rel) = p.text[start..].find(anchor) {
                let abs = start + rel;
                hits.push((p.n, abs, anchor.len(), tab.tab_id.clone()));
                start = abs + 1;
            }
        }
    }
    if hits.is_empty() {
        return Err(DocsError::TextNotFound {
            find: anchor.into(),
            fuzzy_suggestions: vec![],
        });
    }
    let n = occurrence.unwrap_or(1) as usize;
    if n == 0 || n > hits.len() {
        return Err(DocsError::TextNotFound {
            find: anchor.into(),
            fuzzy_suggestions: vec![],
        });
    }
    Ok(hits[n - 1].clone())
}

fn lookup_para(s: &DocumentSnapshot, n: u32) -> &ParagraphSnapshot {
    s.tabs
        .iter()
        .flat_map(|t| t.paragraphs.iter())
        .find(|p| p.n == n)
        .expect("paragraph exists")
}

/// Like `lookup_para`, but if `n` is past the last paragraph, returns
/// the last paragraph in the doc instead.
fn lookup_para_or_eof(s: &DocumentSnapshot, n: u32) -> &ParagraphSnapshot {
    s.tabs
        .iter()
        .flat_map(|t| t.paragraphs.iter())
        .find(|p| p.n == n)
        .or_else(|| s.tabs.iter().flat_map(|t| t.paragraphs.iter()).last())
        .expect("at least one paragraph exists")
}

fn utf16_len(s: &str) -> u32 {
    s.encode_utf16().count() as u32
}

#[allow(clippy::too_many_arguments)]
async fn apply_and_finalize(
    ctx: &GuardContext<'_>,
    doc_id: &DocumentId,
    snap: &DocumentSnapshot,
    requests: Vec<serde_json::Value>,
    kind: ChangeKind,
    paragraph: u32,
    new_markdown: &str,
    tab_id: Option<TabId>,
    lossy: Vec<crate::gdocs::domain::LossyConversion>,
    soft_warnings: Vec<crate::gdocs::domain::HumanChange>,
) -> Result<EditResult, DocsError> {
    if requests.is_empty() {
        return Err(DocsError::InvalidArgs(
            "markdown produced no batchUpdate requests (all elements were lossy)".into(),
        ));
    }
    let result = ctx
        .client
        .batch_update(doc_id, requests, Some(&snap.revision_id))
        .await?;

    // CRITICAL: store the snapshot's revision_id (documents.get format)
    // — not batch_update's writeControl id — so the next guard's
    // revisionId comparison succeeds. See replace_text.rs for the full
    // explanation.
    ctx.cache.invalidate(ctx.session_id, doc_id);
    let fresh = ctx.client.get(doc_id).await?;
    ctx.revisions
        .put_with_snapshot(ctx.session_id, doc_id, &fresh.revision_id, Some(&fresh))
        .await?;
    ctx.cache.put(ctx.session_id, doc_id, fresh.clone());

    Ok(EditResult {
        changes: vec![ChangeRecord {
            kind,
            paragraph,
            before: None,
            after: Some(new_markdown.chars().take(120).collect()),
            tab_id,
        }],
        revision_id_after: result.revision_id_after,
        outline_snapshot: build_outline(&fresh),
        lossy_conversions: lossy,
        pending_human_changes_outside_scope: soft_warnings,
    })
}

fn build_outline(s: &DocumentSnapshot) -> Vec<OutlineEntry> {
    s.tabs
        .iter()
        .flat_map(|t| {
            t.paragraphs.iter().map(|p| OutlineEntry {
                paragraph: p.n,
                tab_id: t.tab_id.clone(),
                kind: p.kind,
                text_preview: p.text.chars().take(80).collect(),
            })
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rejects_markdown_with_table() {
        let md = "Some text\n\n| col1 | col2 |\n|------|------|\n| a    | b    |\n";
        let err = reject_table_markdown(md).unwrap_err();
        assert!(matches!(err, DocsError::InvalidArgs(_)));
    }

    #[test]
    fn accepts_markdown_without_table() {
        let md = "# Heading\n\nA paragraph.\n\n- one\n- two\n";
        assert!(reject_table_markdown(md).is_ok());
    }

    #[test]
    fn validate_image_url_accepts_public_https() {
        assert!(validate_image_url("https://example.com/cat.png").is_ok());
        assert!(validate_image_url("  http://example.com/x.jpg  ").is_ok());
    }

    #[test]
    fn validate_image_url_rejects_non_http_and_empty() {
        // attachment-id-shaped / data URIs / empty all rejected with a hint.
        assert!(matches!(
            validate_image_url("att_123"),
            Err(DocsError::InvalidArgs(_))
        ));
        assert!(matches!(
            validate_image_url("data:image/png;base64,AAAA"),
            Err(DocsError::InvalidArgs(_))
        ));
        assert!(matches!(
            validate_image_url("   "),
            Err(DocsError::InvalidArgs(_))
        ));
    }

    #[test]
    fn validate_image_url_rejects_over_2000_chars() {
        let long = format!("https://example.com/{}", "a".repeat(2000));
        assert!(matches!(
            validate_image_url(&long),
            Err(DocsError::InvalidArgs(_))
        ));
    }

    #[test]
    fn build_insert_image_request_minimal_shape() {
        let req = build_insert_image_request(42, None, "https://x.com/a.png", None, None);
        let img = &req["insertInlineImage"];
        assert_eq!(img["location"]["index"], 42);
        assert!(img["location"].get("tabId").is_none());
        assert_eq!(img["uri"], "https://x.com/a.png");
        // No size → no objectSize key (Docs uses native size).
        assert!(img.get("objectSize").is_none());
    }

    #[test]
    fn build_insert_image_request_with_tab_and_size() {
        let tab = TabId("t.1".to_string());
        let req = build_insert_image_request(
            7,
            Some(&tab),
            "https://x.com/a.png",
            Some(200.0),
            Some(150.0),
        );
        let img = &req["insertInlineImage"];
        assert_eq!(img["location"]["tabId"], "t.1");
        assert_eq!(img["objectSize"]["width"]["magnitude"], 200.0);
        assert_eq!(img["objectSize"]["width"]["unit"], "PT");
        assert_eq!(img["objectSize"]["height"]["magnitude"], 150.0);
    }

    #[test]
    fn accepts_markdown_with_literal_pipes() {
        // Pipes outside tables should NOT trigger rejection.
        let md = "Use the bash pipe operator: `ls | grep foo`\n";
        assert!(reject_table_markdown(md).is_ok());
    }
}

#[cfg(test)]
mod app_tests {
    use super::*;
    use crate::gdocs::application::_test_helpers::*;
    use crate::gdocs::application::co_edit_guard::GuardContext;
    use crate::gdocs::domain::{BatchUpdateResult, ParagraphKind, RevisionId};
    use std::sync::{Arc, Mutex};

    fn expect_get_sequence(
        client: &mut crate::gdocs::domain::traits::MockDocsClient,
        snaps: Vec<DocumentSnapshot>,
    ) {
        let queue = Arc::new(Mutex::new(snaps));
        client.expect_get().returning(move |_| {
            let mut q = queue.lock().unwrap();
            let s = if q.len() > 1 {
                q.remove(0)
            } else {
                q[0].clone()
            };
            Ok(s)
        });
    }

    fn make_batch_update_ok(
        client: &mut crate::gdocs::domain::traits::MockDocsClient,
        rev_after: &'static str,
    ) {
        client.expect_batch_update().returning(move |_, _, _| {
            Ok(BatchUpdateResult {
                revision_id_after: RevisionId(rev_after.into()),
                replies: vec![],
            })
        });
    }

    #[tokio::test]
    async fn insert_after_text_happy() {
        let mut rig = TestRig::new();
        let s = snap(
            "r1",
            vec![(1, ParagraphKind::Paragraph, "intro anchor texto", 1, 20)],
        );
        let s2 = snap(
            "r2",
            vec![(
                1,
                ParagraphKind::Paragraph,
                "intro anchor NUEVO texto",
                1,
                26,
            )],
        );
        expect_get_sequence(&mut rig.client, vec![s, s2]);
        make_batch_update_ok(&mut rig.client, "r2");
        let ctx = GuardContext {
            client: &rig.client,
            cache: &rig.cache,
            revisions: &rig.revisions,
            session_id: "s1",
            sa_email: None,
        };
        let result = super::run_after_text(
            &ctx,
            &doc_id(),
            InsertAfterTextInput {
                anchor: "anchor".into(),
                new_markdown: "NUEVO".into(),
                occurrence: None,
            },
        )
        .await
        .unwrap();
        assert_eq!(result.changes.len(), 1);
        assert_eq!(result.changes[0].kind, ChangeKind::Insert);
    }

    #[tokio::test]
    async fn insert_image_after_text_happy() {
        let mut rig = TestRig::new();
        let s = snap(
            "r1",
            vec![(1, ParagraphKind::Paragraph, "intro anchor texto", 1, 20)],
        );
        let s2 = snap(
            "r2",
            vec![(1, ParagraphKind::Paragraph, "intro anchor texto", 1, 20)],
        );
        expect_get_sequence(&mut rig.client, vec![s, s2]);
        make_batch_update_ok(&mut rig.client, "r2");
        let ctx = GuardContext {
            client: &rig.client,
            cache: &rig.cache,
            revisions: &rig.revisions,
            session_id: "s1",
            sa_email: None,
        };
        let result = super::run_insert_image_after_text(
            &ctx,
            &doc_id(),
            InsertImageAfterTextInput {
                anchor: "anchor".into(),
                image_url: "https://example.com/cat.png".into(),
                occurrence: None,
                width_pt: None,
                height_pt: None,
            },
        )
        .await
        .unwrap();
        assert_eq!(result.changes.len(), 1);
        assert_eq!(result.changes[0].kind, ChangeKind::Insert);
        assert!(result.lossy_conversions.is_empty());
    }

    #[tokio::test]
    async fn insert_image_after_text_rejects_non_http_url() {
        let rig = TestRig::new();
        let ctx = GuardContext {
            client: &rig.client,
            cache: &rig.cache,
            revisions: &rig.revisions,
            session_id: "s1",
            sa_email: None,
        };
        // Bad URL is rejected BEFORE any client call (no get/batch_update mocks set).
        let err = super::run_insert_image_after_text(
            &ctx,
            &doc_id(),
            InsertImageAfterTextInput {
                anchor: "anchor".into(),
                image_url: "att_123".into(),
                occurrence: None,
                width_pt: None,
                height_pt: None,
            },
        )
        .await
        .unwrap_err();
        assert!(matches!(err, DocsError::InvalidArgs(_)));
    }

    #[tokio::test]
    async fn insert_before_text_happy() {
        let mut rig = TestRig::new();
        let s = snap(
            "r1",
            vec![(1, ParagraphKind::Paragraph, "intro anchor texto", 1, 20)],
        );
        let s2 = snap(
            "r2",
            vec![(
                1,
                ParagraphKind::Paragraph,
                "intro NUEVO anchor texto",
                1,
                26,
            )],
        );
        expect_get_sequence(&mut rig.client, vec![s, s2]);
        make_batch_update_ok(&mut rig.client, "r2");
        let ctx = GuardContext {
            client: &rig.client,
            cache: &rig.cache,
            revisions: &rig.revisions,
            session_id: "s1",
            sa_email: None,
        };
        let result = super::run_before_text(
            &ctx,
            &doc_id(),
            InsertBeforeTextInput {
                anchor: "anchor".into(),
                new_markdown: "NUEVO".into(),
                occurrence: None,
            },
        )
        .await
        .unwrap();
        assert_eq!(result.changes.len(), 1);
    }

    #[tokio::test]
    async fn insert_after_text_anchor_not_found() {
        let mut rig = TestRig::new();
        let s = snap(
            "r1",
            vec![(1, ParagraphKind::Paragraph, "intro texto", 1, 12)],
        );
        expect_get_sequence(&mut rig.client, vec![s]);
        let ctx = GuardContext {
            client: &rig.client,
            cache: &rig.cache,
            revisions: &rig.revisions,
            session_id: "s1",
            sa_email: None,
        };
        let err = super::run_after_text(
            &ctx,
            &doc_id(),
            InsertAfterTextInput {
                anchor: "missing".into(),
                new_markdown: "NUEVO".into(),
                occurrence: None,
            },
        )
        .await
        .unwrap_err();
        assert!(matches!(err, DocsError::TextNotFound { .. }));
    }

    #[tokio::test]
    async fn insert_rejects_table_markdown() {
        let rig = TestRig::new();
        let ctx = GuardContext {
            client: &rig.client,
            cache: &rig.cache,
            revisions: &rig.revisions,
            session_id: "s1",
            sa_email: None,
        };
        let md = "| col1 | col2 |\n|------|------|\n| val1 | val2 |";
        let err = super::run_after_text(
            &ctx,
            &doc_id(),
            InsertAfterTextInput {
                anchor: "anchor".into(),
                new_markdown: md.into(),
                occurrence: None,
            },
        )
        .await
        .unwrap_err();
        assert!(matches!(err, DocsError::InvalidArgs(_)));
    }

    #[tokio::test]
    async fn insert_after_text_occurrence_picks_second() {
        let mut rig = TestRig::new();
        let s = snap(
            "r1",
            vec![(
                1,
                ParagraphKind::Paragraph,
                "anchor uno y anchor dos",
                1,
                25,
            )],
        );
        let s2 = snap(
            "r2",
            vec![(
                1,
                ParagraphKind::Paragraph,
                "anchor uno y anchor NUEVO dos",
                1,
                32,
            )],
        );
        expect_get_sequence(&mut rig.client, vec![s, s2]);
        make_batch_update_ok(&mut rig.client, "r2");
        let ctx = GuardContext {
            client: &rig.client,
            cache: &rig.cache,
            revisions: &rig.revisions,
            session_id: "s1",
            sa_email: None,
        };
        let result = super::run_after_text(
            &ctx,
            &doc_id(),
            InsertAfterTextInput {
                anchor: "anchor".into(),
                new_markdown: "NUEVO".into(),
                occurrence: Some(2),
            },
        )
        .await
        .unwrap();
        assert_eq!(result.changes.len(), 1);
    }

    #[tokio::test]
    async fn insert_image_from_bytes_uploads_makes_public_inserts_then_deletes() {
        let mut rig = TestRig::new();
        let s = snap(
            "r1",
            vec![(1, ParagraphKind::Paragraph, "intro anchor texto", 1, 20)],
        );
        let s2 = snap(
            "r2",
            vec![(1, ParagraphKind::Paragraph, "intro anchor texto", 1, 20)],
        );
        rig.client
            .expect_upload_image_to_drive()
            .returning(|_, _, _| Ok("FID9".to_string()));
        rig.client
            .expect_set_anyone_reader()
            .withf(|f| f == "FID9")
            .returning(|_| Ok(()));
        expect_get_sequence(&mut rig.client, vec![s, s2]);
        make_batch_update_ok(&mut rig.client, "r2");
        rig.client
            .expect_delete_drive_file()
            .withf(|f| f == "FID9")
            .returning(|_| Ok(()));
        let ctx = GuardContext {
            client: &rig.client,
            cache: &rig.cache,
            revisions: &rig.revisions,
            session_id: "s1",
            sa_email: None,
        };
        let (result, warnings) = super::run_insert_image_from_bytes(
            &ctx,
            &doc_id(),
            InsertImageAfterTextInput {
                anchor: "anchor".into(),
                image_url: String::new(),
                occurrence: None,
                width_pt: None,
                height_pt: None,
            },
            vec![1, 2, 3],
            "image/png",
        )
        .await
        .unwrap();
        assert_eq!(result.changes.len(), 1);
        assert!(warnings.is_empty());
    }

    #[tokio::test]
    async fn insert_image_from_bytes_deletes_temp_file_when_insert_fails() {
        let mut rig = TestRig::new();
        let s = snap(
            "r1",
            vec![(1, ParagraphKind::Paragraph, "no match here", 1, 14)],
        );
        rig.client
            .expect_upload_image_to_drive()
            .returning(|_, _, _| Ok("FIDx".into()));
        rig.client.expect_set_anyone_reader().returning(|_| Ok(()));
        expect_get_sequence(&mut rig.client, vec![s]); // anchor not found -> insert errors
                                                       // MUST clean up the uploaded file:
        rig.client
            .expect_delete_drive_file()
            .withf(|f| f == "FIDx")
            .times(1)
            .returning(|_| Ok(()));
        let ctx = GuardContext {
            client: &rig.client,
            cache: &rig.cache,
            revisions: &rig.revisions,
            session_id: "s1",
            sa_email: None,
        };
        let err = super::run_insert_image_from_bytes(
            &ctx,
            &doc_id(),
            InsertImageAfterTextInput {
                anchor: "anchor".into(),
                image_url: String::new(),
                occurrence: None,
                width_pt: None,
                height_pt: None,
            },
            vec![1],
            "image/png",
        )
        .await
        .unwrap_err();
        assert!(matches!(err, DocsError::TextNotFound { .. }));
    }

    #[tokio::test]
    async fn insert_image_from_bytes_soft_warns_when_cleanup_fails() {
        let mut rig = TestRig::new();
        let s = snap(
            "r1",
            vec![(1, ParagraphKind::Paragraph, "intro anchor texto", 1, 20)],
        );
        let s2 = snap(
            "r2",
            vec![(1, ParagraphKind::Paragraph, "intro anchor texto", 1, 20)],
        );
        rig.client
            .expect_upload_image_to_drive()
            .returning(|_, _, _| Ok("FIDz".into()));
        rig.client.expect_set_anyone_reader().returning(|_| Ok(()));
        expect_get_sequence(&mut rig.client, vec![s, s2]);
        make_batch_update_ok(&mut rig.client, "r2");
        rig.client
            .expect_delete_drive_file()
            .returning(|_| Err(DocsError::Http("boom".into())));
        let ctx = GuardContext {
            client: &rig.client,
            cache: &rig.cache,
            revisions: &rig.revisions,
            session_id: "s1",
            sa_email: None,
        };
        let (result, warnings) = super::run_insert_image_from_bytes(
            &ctx,
            &doc_id(),
            InsertImageAfterTextInput {
                anchor: "anchor".into(),
                image_url: String::new(),
                occurrence: None,
                width_pt: None,
                height_pt: None,
            },
            vec![1],
            "image/png",
        )
        .await
        .unwrap();
        assert_eq!(result.changes.len(), 1);
        assert_eq!(warnings.len(), 1);
        assert!(warnings[0].contains("FIDz"));
    }

    #[test]
    fn image_ext_for_mime_rejects_non_image() {
        assert_eq!(super::image_ext_for_mime("image/png"), Some("png"));
        assert_eq!(super::image_ext_for_mime("image/jpeg"), Some("jpg"));
        assert_eq!(super::image_ext_for_mime("application/pdf"), None);
    }

    #[tokio::test]
    async fn insert_between_happy() {
        let mut rig = TestRig::new();
        let s = snap(
            "r1",
            vec![
                (1, ParagraphKind::Heading2, "Sección A", 1, 11),
                (2, ParagraphKind::Paragraph, "contenido A", 11, 23),
                (3, ParagraphKind::Heading2, "Sección B", 23, 33),
            ],
        );
        let s2 = snap(
            "r2",
            vec![
                (1, ParagraphKind::Heading2, "Sección A", 1, 11),
                (2, ParagraphKind::Paragraph, "NUEVO", 11, 17),
                (3, ParagraphKind::Paragraph, "contenido A", 17, 29),
                (4, ParagraphKind::Heading2, "Sección B", 29, 39),
            ],
        );
        expect_get_sequence(&mut rig.client, vec![s, s2]);
        make_batch_update_ok(&mut rig.client, "r2");
        let ctx = GuardContext {
            client: &rig.client,
            cache: &rig.cache,
            revisions: &rig.revisions,
            session_id: "s1",
            sa_email: None,
        };
        let result = super::run_between(
            &ctx,
            &doc_id(),
            InsertBetweenInput {
                after_heading: "## Sección A".into(),
                before_heading: Some("## Sección B".into()),
                new_markdown: "NUEVO".into(),
            },
        )
        .await
        .unwrap();
        assert_eq!(result.changes.len(), 1);
    }
}
