//! `image_generation` node. Generates one or more images from a text prompt
//! using either OpenAI (`gpt-image-1` / `dall-e-3`) or Google Vertex AI
//! Imagen 4. Generated bytes are persisted via the injected
//! [`OutputStorageRepository`], so the node returns small handles
//! (`attachment_id`, `url`) rather than embedding raw image bytes.
//!
//! Spec: docs/superpowers/plans/2026-05-19-multimedia-generation-nodes.md
//!
//! ## Config schema
//!
//! ```json
//! {
//!   "provider": "openai" | "google",
//!   "model": "gpt-image-1" | "dall-e-3" | "imagen-4.0-generate-001",
//!   "api_key": "${OPENAI_API_KEY}",            // openai only
//!   "prompt": "...",
//!   "size": "1024x1024",                       // optional
//!   "quality": "low" | "medium" | "high" | "auto",  // openai only, optional
//!   "n": 1,                                    // optional, default 1
//!   "google_project_id": "...",                // optional — falls back to env (see below)
//!   "google_location": "us-central1"           // optional, default us-central1
//! }
//! ```
//!
//! ## Best practice for Vertex (`provider=google`)
//!
//! **Do NOT set `google_project_id` / `google_location` in the graph JSON.**
//! Leave them off and let the worker resolve them from the canonical Google
//! Cloud env vars at runtime:
//!
//! | Field             | Primary env var         | Fallback env var      | Built-in default |
//! |-------------------|-------------------------|-----------------------|------------------|
//! | google_project_id | `GOOGLE_CLOUD_PROJECT`  | `GOOGLE_PROJECT_ID`   | none (required)  |
//! | google_location   | `GOOGLE_CLOUD_LOCATION` | `GOOGLE_LOCATION`     | `us-central1`    |
//!
//! Why this matters: the same graph JSON ships unchanged across dev / staging
//! / prod environments — each environment's worker injects its own project id
//! through the deploy config. Hard-coding the project in the JSON couples the
//! graph to one environment and forces JSON edits on promotion.
//!
//! Override the env defaults from the graph only when a single graph needs to
//! target a project other than the worker's runtime project (rare).
//!
//! ## Output shape
//!
//! ```json
//! {
//!   "output": {
//!     "images": [{
//!       "attachment_id": "...",
//!       "url": "...",
//!       "mime_type": "image/png",
//!       "size_bytes": 123456,
//!       "description": "Image generated with <model>: <prompt prefix>"
//!     }],
//!     "provider": "openai",
//!     "model": "gpt-image-1"
//!   }
//! }
//! ```

use std::error::Error as StdError;
use std::sync::Arc;
use std::time::{Duration, Instant};

use async_trait::async_trait;
use base64::Engine;
use serde_json::{json, Value};
use tokio::sync::Mutex;

use crate::dag_engine::application::secure_value_service::SecureValueService;
use crate::dag_engine::domain::node::{ExecutableNode, NodeInputs};
use crate::dag_engine::domain::observer::ExecutionObserver;
use crate::llm::domain::attachments::{AttachmentSource, UpsertAttachmentInput};
use crate::llm::domain::{AttachmentRegistry, ProviderKind};
use crate::storage::domain::{OutputStorageRepository, StoreRequest};

const VERTEX_SCOPE: &str = "https://www.googleapis.com/auth/cloud-platform";

#[derive(Debug, Clone)]
struct CachedToken {
    token: String,
    expires_at: Instant,
}

pub struct ImageGenerationNode {
    storage: Arc<dyn OutputStorageRepository>,
    http: reqwest::Client,
    secure_values: Option<Arc<SecureValueService>>,
    /// Optional registry. When present, every successful generation is
    /// upserted with `provider: Generated` so that `load_attachment` can
    /// later resolve the bytes (cross-provider lazy upload).
    attachment_registry: Option<Arc<dyn AttachmentRegistry>>,
    /// Cached Vertex AI bearer token. Rebuilt lazily when expired (~50 min TTL).
    vertex_token: Mutex<Option<CachedToken>>,

    /// Test-only override of the OpenAI base URL (default
    /// `https://api.openai.com`). Lets unit tests point the node at a
    /// `wiremock` server.
    #[cfg(test)]
    test_openai_base_url: Option<String>,
}

impl ImageGenerationNode {
    pub fn new(storage: Arc<dyn OutputStorageRepository>) -> Self {
        Self {
            storage,
            http: reqwest::Client::new(),
            secure_values: None,
            attachment_registry: None,
            vertex_token: Mutex::new(None),
            #[cfg(test)]
            test_openai_base_url: None,
        }
    }

    pub fn with_secure_values(mut self, svc: Arc<SecureValueService>) -> Self {
        self.secure_values = Some(svc);
        self
    }

    pub fn with_attachment_registry(mut self, reg: Arc<dyn AttachmentRegistry>) -> Self {
        self.attachment_registry = Some(reg);
        self
    }

    #[cfg(test)]
    fn with_openai_base_url(mut self, url: String) -> Self {
        self.test_openai_base_url = Some(url);
        self
    }

    /// Resolve `${VAR}` placeholders against the process environment. Pass
    /// non-placeholder strings through unchanged. Mirrors the convention used
    /// by other adapters (`tavily_client`, `llm`).
    fn resolve_env_var(value: &str) -> Result<String, String> {
        if value.starts_with("${") && value.ends_with('}') {
            let var = &value[2..value.len() - 1];
            std::env::var(var)
                .map_err(|_| format!("env var {var} not set (referenced by image_generation)"))
        } else {
            Ok(value.to_string())
        }
    }

    fn openai_base_url(&self) -> &str {
        #[cfg(test)]
        if let Some(url) = &self.test_openai_base_url {
            return url.as_str();
        }
        "https://api.openai.com"
    }
}

#[async_trait]
impl ExecutableNode for ImageGenerationNode {
    async fn execute(
        &self,
        inputs: &NodeInputs,
        config: &Value,
        _state: &mut Value,
        _observer: Option<Arc<dyn ExecutionObserver>>,
    ) -> Result<Value, Box<dyn StdError + Send + Sync>> {
        // Engine-injected scope identifiers — forwarded to the storage
        // adapter so the API can derive the conversation-scoped path
        // (chat-attachments/<userId>/<agentSessionDbId>/generated/...).
        // Both default to None for ad-hoc CLI runs.
        let session_id = inputs
            .get("__colmena_session_id")
            .and_then(|v| v.as_str())
            .map(String::from);
        let agent_session_id = inputs
            .get("__colmena_agent_session_id")
            .and_then(|v| v.as_str())
            .map(String::from);

        // 1) Inject secure values (decrypts <value_N> placeholders) into a
        //    copy so the caller's config is untouched.
        let mut cfg = config.clone();
        if let Some(svc) = &self.secure_values {
            // Use the real session_id when present so secure-value lookups
            // hit the right scope; fall back to "default" for CLI runs.
            let svc_session = session_id.as_deref().unwrap_or("default");
            let _ = svc
                .inject_secrets(&mut cfg, svc_session, agent_session_id.as_deref())
                .await?;
        }

        // Provider/model/api_key are infrastructure config. We read them from
        // both `inputs` and `config` (inputs first) because when the node is
        // invoked as an LLM tool, the executor passes `config={}` and merges
        // all `node_schema.fixed` values into `inputs` instead — see
        // `dag_tool_executor.rs` line ~934. As a standalone DAG node, the
        // values arrive via `config`. Reading both paths makes the same node
        // work in both call sites.
        let provider = inputs
            .get("provider")
            .and_then(|v| v.as_str())
            .map(String::from)
            .or_else(|| {
                cfg.get("provider")
                    .and_then(|v| v.as_str())
                    .map(String::from)
            })
            .ok_or("image_generation: provider is required (openai|google)")?;
        let model = inputs
            .get("model")
            .and_then(|v| v.as_str())
            .map(String::from)
            .or_else(|| cfg.get("model").and_then(|v| v.as_str()).map(String::from))
            .ok_or("image_generation: model is required")?;

        // Inputs-over-config for fields the LLM (or upstream node) may control —
        // prompt/size/quality/n. This matches the tavily_client convention and
        // enables both DAG chaining (via edges) and tool use.
        let prompt = inputs
            .get("prompt")
            .and_then(|v| v.as_str())
            .map(String::from)
            .or_else(|| cfg.get("prompt").and_then(|v| v.as_str()).map(String::from))
            .ok_or("image_generation: prompt is required (via inputs or config)")?;
        let n = inputs
            .get("n")
            .and_then(|v| v.as_u64())
            .or_else(|| cfg.get("n").and_then(|v| v.as_u64()))
            .unwrap_or(1)
            .clamp(1, 10) as u32;
        let size = inputs
            .get("size")
            .and_then(|v| v.as_str())
            .or_else(|| cfg.get("size").and_then(|v| v.as_str()))
            .unwrap_or("1024x1024")
            .to_string();

        // 2) Provider dispatch returns Vec<(bytes, mime)>.
        let images: Vec<(Vec<u8>, String)> = match provider.as_str() {
            "openai" => {
                let api_key_raw = inputs
                    .get("api_key")
                    .and_then(|v| v.as_str())
                    .or_else(|| cfg.get("api_key").and_then(|v| v.as_str()))
                    .ok_or("image_generation: api_key is required when provider=openai")?;
                let api_key = Self::resolve_env_var(api_key_raw)?;
                let quality = inputs
                    .get("quality")
                    .and_then(|v| v.as_str())
                    .map(String::from)
                    .or_else(|| {
                        cfg.get("quality")
                            .and_then(|v| v.as_str())
                            .map(String::from)
                    });
                self.openai_generate(&api_key, &model, &prompt, n, &size, quality.as_deref())
                    .await?
            }
            "google" => {
                // Project + location follow the dual-source pattern (inputs → config)
                // and additionally fall back to the canonical Google Cloud env vars
                // that gcloud, the Vertex client libraries, and Cloud Run all use.
                // This lets the same graph run unchanged in local dev (where the
                // env vars are set in `.env`) and in prod (where the deploy may
                // inject them via Cloud Run settings or rely on the runtime
                // metadata).
                let project = inputs
                    .get("google_project_id")
                    .and_then(|v| v.as_str())
                    .map(String::from)
                    .or_else(|| {
                        cfg.get("google_project_id")
                            .and_then(|v| v.as_str())
                            .map(String::from)
                    })
                    .or_else(|| std::env::var("GOOGLE_CLOUD_PROJECT").ok())
                    .or_else(|| std::env::var("GOOGLE_PROJECT_ID").ok())
                    .ok_or(
                        "image_generation: google_project_id is required when provider=google \
                         (provide via config/inputs, or set GOOGLE_CLOUD_PROJECT env var)",
                    )?;
                let location = inputs
                    .get("google_location")
                    .and_then(|v| v.as_str())
                    .map(String::from)
                    .or_else(|| {
                        cfg.get("google_location")
                            .and_then(|v| v.as_str())
                            .map(String::from)
                    })
                    .or_else(|| std::env::var("GOOGLE_CLOUD_LOCATION").ok())
                    .or_else(|| std::env::var("GOOGLE_LOCATION").ok())
                    .unwrap_or_else(|| "us-central1".to_string());
                self.vertex_generate(&project, &location, &model, &prompt, n)
                    .await?
            }
            other => {
                return Err(format!(
                    "image_generation: unknown provider '{other}' (expected openai|google)"
                )
                .into());
            }
        };

        if images.is_empty() {
            return Err("image_generation: provider returned 0 images".into());
        }

        // 3) Persist each image through the storage port.
        let prompt_preview: String = prompt.chars().take(80).collect();
        let mut out_images = Vec::with_capacity(images.len());
        for (i, (bytes, mime_type)) in images.into_iter().enumerate() {
            let filename = match mime_type.as_str() {
                "image/png" => format!("image_{}.png", i),
                "image/jpeg" => format!("image_{}.jpg", i),
                "image/webp" => format!("image_{}.webp", i),
                _ => format!("image_{}.bin", i),
            };
            let stored = self
                .storage
                .store(StoreRequest {
                    bytes,
                    mime_type,
                    filename,
                    session_id: session_id.clone(),
                    agent_session_id: agent_session_id.clone(),
                })
                .await
                .map_err(|e| -> Box<dyn StdError + Send + Sync> { Box::new(e) })?;

            // Register the generated artifact so `load_attachment` can later
            // resolve it. Fail-soft: a registry error must not fail generation.
            if let (Some(reg), Some(agent_sid)) =
                (self.attachment_registry.as_ref(), agent_session_id.as_ref())
            {
                let description = format!("Image generated with {}: {}", model, prompt_preview);
                let upsert = UpsertAttachmentInput {
                    agent_session_id: agent_sid.clone(),
                    document_id: stored.storage_key.clone(),
                    provider: ProviderKind::Generated,
                    // For `provider: Generated` rows, provider_file_id holds
                    // the canonical storage_key. Cross-provider upload reads
                    // bytes via OutputStorageRepository.read(this).
                    provider_file_id: stored.storage_key.clone(),
                    mime_type: stored.mime_type.clone(),
                    filename: stored.filename.clone(),
                    size_bytes: Some(stored.size_bytes),
                    label: None,
                    description: Some(description),
                    source: AttachmentSource::SignedUrl(stored.read_url.clone()),
                };
                if let Err(e) = reg.upsert(upsert).await {
                    tracing::warn!(
                        target: "colmena::image_generation",
                        error = %e,
                        storage_key = %stored.storage_key,
                        "failed to register generated image in attachment registry — \
                         load_attachment will not see this output"
                    );
                }
            }

            out_images.push(json!({
                "attachment_id": stored.storage_key,
                "url": stored.read_url,
                "mime_type": stored.mime_type,
                "size_bytes": stored.size_bytes,
                "description": format!("Image generated with {}: {}", model, prompt_preview),
            }));
        }

        Ok(json!({
            "output": {
                "images": out_images,
                "provider": provider,
                "model": model,
            }
        }))
    }

    fn schema(&self) -> Value {
        json!({
            "inputs": {},
            "outputs": { "output": "object" },
            "config": {
                "provider": "string (required) — openai | google",
                "model": "string (required) — gpt-image-1 | dall-e-3 | imagen-4.0-generate-001",
                "api_key": "string (openai only) — supports ${ENV_VAR} or secure-value placeholders",
                "prompt": "string (required)",
                "size": "string (optional, default 1024x1024)",
                "quality": "string (openai only, optional) — low | medium | high | auto",
                "n": "integer (optional, default 1, max 10)",
                "google_project_id": "string (required if provider=google)",
                "google_location": "string (optional, default us-central1)"
            }
        })
    }

    fn description(&self) -> Option<&str> {
        Some(
            "Generate one or more images from a text prompt. Supports OpenAI \
             (gpt-image-1, dall-e-3) and Google Vertex AI Imagen 4. Returns an \
             array of attachments — each with `attachment_id` (stable handle), \
             `url` (signed read URL or data: URI), `mime_type`, and `size_bytes`.",
        )
    }

    fn default_input(&self) -> Option<&str> {
        Some("prompt")
    }

    fn default_output(&self) -> Option<&str> {
        // Top-level key inside the returned Value. Downstream nodes that don't
        // specify a JSON pointer will receive `output` (the object containing
        // `images`, `provider`, `model`).
        Some("output")
    }
}

impl ImageGenerationNode {
    async fn openai_generate(
        &self,
        api_key: &str,
        model: &str,
        prompt: &str,
        n: u32,
        size: &str,
        quality: Option<&str>,
    ) -> Result<Vec<(Vec<u8>, String)>, Box<dyn StdError + Send + Sync>> {
        let mut body = json!({
            "model": model,
            "prompt": prompt,
            "n": n,
            "size": size,
        });
        if let Some(q) = quality {
            body["quality"] = json!(q);
        }

        let url = format!("{}/v1/images/generations", self.openai_base_url());
        let resp = self
            .http
            .post(&url)
            .bearer_auth(api_key)
            .json(&body)
            .send()
            .await?;

        if !resp.status().is_success() {
            let status = resp.status();
            let body = resp.text().await.unwrap_or_default();
            return Err(
                format!("openai images/generations failed: status={status} body={body}").into(),
            );
        }

        let payload: Value = resp.json().await?;
        let data = payload
            .get("data")
            .and_then(|d| d.as_array())
            .ok_or("openai response missing `data` array")?;
        if data.is_empty() {
            return Err("openai response `data` array is empty".into());
        }

        let mut images = Vec::with_capacity(data.len());
        for entry in data {
            // gpt-image-1 returns b64_json; dall-e-3 returns url unless asked otherwise.
            if let Some(b64) = entry.get("b64_json").and_then(|v| v.as_str()) {
                let bytes = base64::engine::general_purpose::STANDARD
                    .decode(b64)
                    .map_err(|e| format!("openai b64 decode failed: {e}"))?;
                images.push((bytes, "image/png".to_string()));
            } else if let Some(url) = entry.get("url").and_then(|v| v.as_str()) {
                let bytes = self.http.get(url).send().await?.bytes().await?.to_vec();
                images.push((bytes, "image/png".to_string()));
            } else {
                return Err("openai response entry missing both b64_json and url".into());
            }
        }
        Ok(images)
    }

    async fn vertex_generate(
        &self,
        project: &str,
        location: &str,
        model: &str,
        prompt: &str,
        n: u32,
    ) -> Result<Vec<(Vec<u8>, String)>, Box<dyn StdError + Send + Sync>> {
        let token = self.get_vertex_token().await?;
        let url = format!(
            "https://{location}-aiplatform.googleapis.com/v1/projects/{project}/locations/{location}/publishers/google/models/{model}:predict"
        );

        let body = json!({
            "instances": [{ "prompt": prompt }],
            "parameters": { "sampleCount": n }
        });

        let resp = self
            .http
            .post(&url)
            .bearer_auth(&token)
            .json(&body)
            .send()
            .await?;

        if !resp.status().is_success() {
            let status = resp.status();
            let body = resp.text().await.unwrap_or_default();
            return Err(
                format!("vertex imagen :predict failed: status={status} body={body}").into(),
            );
        }

        let payload: Value = resp.json().await?;
        let predictions = payload
            .get("predictions")
            .and_then(|p| p.as_array())
            .ok_or("vertex response missing `predictions` array")?;
        if predictions.is_empty() {
            return Err("vertex response `predictions` array is empty".into());
        }

        let mut images = Vec::with_capacity(predictions.len());
        for entry in predictions {
            let b64 = entry
                .get("bytesBase64Encoded")
                .and_then(|v| v.as_str())
                .ok_or("vertex prediction missing bytesBase64Encoded")?;
            let mime = entry
                .get("mimeType")
                .and_then(|v| v.as_str())
                .unwrap_or("image/png")
                .to_string();
            let bytes = base64::engine::general_purpose::STANDARD
                .decode(b64)
                .map_err(|e| format!("vertex b64 decode failed: {e}"))?;
            images.push((bytes, mime));
        }
        Ok(images)
    }

    /// Returns a cached Vertex AI bearer token, refreshing via `yup-oauth2`
    /// when within 60 s of expiry. Credentials are discovered via
    /// Application Default Credentials, which tries — in order:
    ///   1. `GOOGLE_APPLICATION_CREDENTIALS` (path to a service account JSON)
    ///   2. The well-known `gcloud` user credentials location
    ///   3. The GCE/Cloud Run metadata server (runtime service account)
    ///
    /// This means local dev with `gcloud auth application-default login` and
    /// Cloud Run deploys both work without setting any env var explicitly.
    async fn get_vertex_token(&self) -> Result<String, Box<dyn StdError + Send + Sync>> {
        use yup_oauth2::authenticator::ApplicationDefaultCredentialsTypes;
        use yup_oauth2::{
            ApplicationDefaultCredentialsAuthenticator, ApplicationDefaultCredentialsFlowOpts,
        };

        let mut cache = self.vertex_token.lock().await;
        if let Some(c) = &*cache {
            if c.expires_at > Instant::now() + Duration::from_secs(60) {
                return Ok(c.token.clone());
            }
        }

        let opts = ApplicationDefaultCredentialsFlowOpts::default();
        let auth = match ApplicationDefaultCredentialsAuthenticator::builder(opts).await {
            ApplicationDefaultCredentialsTypes::InstanceMetadata(builder) => builder
                .build()
                .await
                .map_err(|e| format!("failed to build Vertex metadata authenticator: {e}"))?,
            ApplicationDefaultCredentialsTypes::ServiceAccount(builder) => builder
                .build()
                .await
                .map_err(|e| format!("failed to build Vertex service-account authenticator: {e}"))?,
        };

        let token = auth
            .token(&[VERTEX_SCOPE])
            .await
            .map_err(|e| format!("failed to fetch Vertex access token: {e}"))?;
        let access = token
            .token()
            .ok_or("Vertex authenticator returned no access token")?
            .to_string();

        // Conservative ~50 min TTL; yup-oauth2 tokens typically last 1 h.
        let expires_at = Instant::now() + Duration::from_secs(50 * 60);
        *cache = Some(CachedToken {
            token: access.clone(),
            expires_at,
        });
        Ok(access)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::storage::domain::{MockOutputStorageRepository, StoredOutput};
    use mockall::predicate::always;
    use serde_json::json;
    use std::collections::HashMap;
    use wiremock::matchers::{header_exists, method, path};
    use wiremock::{Mock, MockServer, ResponseTemplate};

    fn stored_ok(key: &str) -> StoredOutput {
        StoredOutput {
            storage_key: key.to_string(),
            read_url: "data:image/png;base64,XX".to_string(),
            mime_type: "image/png".into(),
            filename: "image_0.png".into(),
            size_bytes: 2,
        }
    }

    #[tokio::test]
    async fn openai_happy_path_returns_one_image_and_calls_storage_once() {
        let server = MockServer::start().await;

        // OpenAI gpt-image-1 always returns b64_json. "AAA" is base64 for [0,0,0].
        Mock::given(method("POST"))
            .and(path("/v1/images/generations"))
            .and(header_exists("authorization"))
            .respond_with(ResponseTemplate::new(200).set_body_json(json!({
                "data": [{ "b64_json": "AAAA" }]
            })))
            .mount(&server)
            .await;

        let mut storage = MockOutputStorageRepository::new();
        storage
            .expect_store()
            .times(1)
            .with(always())
            .returning(|_req| Ok(stored_ok("k1")));

        let node = ImageGenerationNode::new(Arc::new(storage)).with_openai_base_url(server.uri());

        let config = json!({
            "provider": "openai",
            "model": "gpt-image-1",
            "api_key": "sk-test",
            "prompt": "a tiny red circle",
        });
        let inputs: NodeInputs = HashMap::new();
        let mut state = json!({});
        let out = node
            .execute(&inputs, &config, &mut state, None)
            .await
            .expect("execute ok");

        let images = out
            .pointer("/output/images")
            .and_then(|v| v.as_array())
            .expect("output.images array");
        assert_eq!(images.len(), 1);
        assert_eq!(images[0]["attachment_id"], "k1");
        assert_eq!(images[0]["mime_type"], "image/png");
        assert_eq!(out["output"]["provider"], "openai");
        assert_eq!(out["output"]["model"], "gpt-image-1");
    }

    #[tokio::test]
    async fn openai_n_2_storage_called_twice() {
        let server = MockServer::start().await;

        Mock::given(method("POST"))
            .and(path("/v1/images/generations"))
            .respond_with(ResponseTemplate::new(200).set_body_json(json!({
                "data": [
                    { "b64_json": "AAAA" },
                    { "b64_json": "AAAB" },
                ]
            })))
            .mount(&server)
            .await;

        let mut storage = MockOutputStorageRepository::new();
        storage
            .expect_store()
            .times(2)
            .returning(|_| Ok(stored_ok("k")));

        let node = ImageGenerationNode::new(Arc::new(storage)).with_openai_base_url(server.uri());

        let config = json!({
            "provider": "openai",
            "model": "gpt-image-1",
            "api_key": "sk-test",
            "prompt": "two circles",
            "n": 2,
        });
        let out = node
            .execute(&HashMap::new(), &config, &mut json!({}), None)
            .await
            .unwrap();
        assert_eq!(out["output"]["images"].as_array().unwrap().len(), 2);
    }

    #[tokio::test]
    async fn openai_error_400_propagates() {
        let server = MockServer::start().await;

        Mock::given(method("POST"))
            .and(path("/v1/images/generations"))
            .respond_with(ResponseTemplate::new(400).set_body_string("bad prompt"))
            .mount(&server)
            .await;

        let storage = MockOutputStorageRepository::new(); // never called
        let node = ImageGenerationNode::new(Arc::new(storage)).with_openai_base_url(server.uri());

        let config = json!({
            "provider": "openai",
            "model": "gpt-image-1",
            "api_key": "sk-test",
            "prompt": "x",
        });
        let err = node
            .execute(&HashMap::new(), &config, &mut json!({}), None)
            .await
            .unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("400"));
        assert!(msg.contains("bad prompt"));
    }

    #[tokio::test]
    async fn missing_provider_errors() {
        let storage = MockOutputStorageRepository::new();
        let node = ImageGenerationNode::new(Arc::new(storage));

        let config = json!({ "model": "gpt-image-1", "prompt": "x", "api_key": "k" });
        let err = node
            .execute(&HashMap::new(), &config, &mut json!({}), None)
            .await
            .unwrap_err();
        assert!(err.to_string().contains("provider"));
    }

    #[tokio::test]
    async fn provider_can_arrive_via_inputs_for_tool_use() {
        let server = MockServer::start().await;
        Mock::given(method("POST"))
            .and(path("/v1/images/generations"))
            .respond_with(ResponseTemplate::new(200).set_body_json(json!({
                "data": [{ "b64_json": "AAAA" }]
            })))
            .mount(&server)
            .await;

        let mut storage = MockOutputStorageRepository::new();
        storage
            .expect_store()
            .times(1)
            .returning(|_| Ok(stored_ok("k")));

        let node = ImageGenerationNode::new(Arc::new(storage)).with_openai_base_url(server.uri());

        // Simulates the tool-execution path: executor passes config={} and
        // merges fixed values into inputs.
        let config = json!({});
        let mut inputs: NodeInputs = HashMap::new();
        inputs.insert("provider".into(), json!("openai"));
        inputs.insert("model".into(), json!("gpt-image-1"));
        inputs.insert("api_key".into(), json!("sk-test"));
        inputs.insert("prompt".into(), json!("a cat"));
        inputs.insert("size".into(), json!("1024x1024"));

        node.execute(&inputs, &config, &mut json!({}), None)
            .await
            .expect("execute ok when all infra fields come via inputs");
    }

    #[tokio::test]
    async fn unknown_provider_errors() {
        let storage = MockOutputStorageRepository::new();
        let node = ImageGenerationNode::new(Arc::new(storage));

        let config = json!({
            "provider": "midjourney",
            "model": "v6",
            "prompt": "x",
            "api_key": "k",
        });
        let err = node
            .execute(&HashMap::new(), &config, &mut json!({}), None)
            .await
            .unwrap_err();
        assert!(err.to_string().contains("unknown provider"));
    }

    #[tokio::test]
    async fn google_without_project_errors() {
        // Defensive cleanup in case another test left the env var set in this
        // process. Both fallback names are checked by the node.
        std::env::remove_var("GOOGLE_CLOUD_PROJECT");
        std::env::remove_var("GOOGLE_PROJECT_ID");

        let storage = MockOutputStorageRepository::new();
        let node = ImageGenerationNode::new(Arc::new(storage));

        let config = json!({
            "provider": "google",
            "model": "imagen-4.0-generate-001",
            "prompt": "x",
        });
        let err = node
            .execute(&HashMap::new(), &config, &mut json!({}), None)
            .await
            .unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("google_project_id"));
        // The error message should hint that env vars are also a valid source,
        // so the user knows the two ways to fix it.
        assert!(
            msg.contains("GOOGLE_CLOUD_PROJECT"),
            "error message should mention the env-var fallback, got: {msg}"
        );
    }


    #[tokio::test]
    async fn session_ids_forwarded_to_storage_when_present_in_inputs() {
        let server = MockServer::start().await;

        Mock::given(method("POST"))
            .and(path("/v1/images/generations"))
            .respond_with(ResponseTemplate::new(200).set_body_json(json!({
                "data": [{ "b64_json": "AAAA" }]
            })))
            .mount(&server)
            .await;

        let mut storage = MockOutputStorageRepository::new();
        // Assert the engine-injected session ids propagate verbatim into StoreRequest.
        storage
            .expect_store()
            .times(1)
            .withf(|req| {
                req.session_id.as_deref() == Some("ses_abc")
                    && req.agent_session_id.as_deref() == Some("agent_xyz")
            })
            .returning(|_| Ok(stored_ok("k")));

        let node = ImageGenerationNode::new(Arc::new(storage)).with_openai_base_url(server.uri());

        let config = json!({
            "provider": "openai",
            "model": "gpt-image-1",
            "api_key": "sk-test",
            "prompt": "x",
        });

        let mut inputs: NodeInputs = HashMap::new();
        inputs.insert("__colmena_session_id".into(), json!("ses_abc"));
        inputs.insert("__colmena_agent_session_id".into(), json!("agent_xyz"));

        node.execute(&inputs, &config, &mut json!({}), None)
            .await
            .expect("execute ok");
    }

    #[tokio::test]
    async fn inputs_prompt_overrides_config() {
        let server = MockServer::start().await;

        // Capture the prompt that hit the OpenAI mock.
        Mock::given(method("POST"))
            .and(path("/v1/images/generations"))
            .respond_with(ResponseTemplate::new(200).set_body_json(json!({
                "data": [{ "b64_json": "AAAA" }]
            })))
            .mount(&server)
            .await;

        let mut storage = MockOutputStorageRepository::new();
        storage
            .expect_store()
            .times(1)
            .returning(|_| Ok(stored_ok("k")));

        let node = ImageGenerationNode::new(Arc::new(storage)).with_openai_base_url(server.uri());

        // config.prompt and inputs.prompt both set — inputs must win.
        let mut config = json!({
            "provider": "openai",
            "model": "gpt-image-1",
            "api_key": "sk-test",
            "prompt": "config prompt — should NOT be used",
        });
        config["size"] = json!("1024x1024");
        let mut inputs: NodeInputs = HashMap::new();
        inputs.insert("prompt".into(), json!("inputs prompt — should win"));

        let out = node
            .execute(&inputs, &config, &mut json!({}), None)
            .await
            .expect("execute ok");
        let desc = out["output"]["images"][0]["description"].as_str().unwrap();
        assert!(
            desc.contains("inputs prompt"),
            "description should reflect the inputs prompt, got: {desc}"
        );
    }

    #[tokio::test]
    async fn openai_env_var_api_key_resolved() {
        let server = MockServer::start().await;

        Mock::given(method("POST"))
            .and(path("/v1/images/generations"))
            .and(header_exists("authorization"))
            .respond_with(ResponseTemplate::new(200).set_body_json(json!({
                "data": [{ "b64_json": "AAAA" }]
            })))
            .mount(&server)
            .await;

        // Set env var BEFORE constructing the node — resolve_env_var reads at execute time.
        // SAFETY: the variable name is unique to this test to avoid races with parallel tests.
        std::env::set_var("__COLMENA_TEST_IMG_GEN_KEY__", "sk-from-env");

        let mut storage = MockOutputStorageRepository::new();
        storage
            .expect_store()
            .times(1)
            .returning(|_| Ok(stored_ok("k")));

        let node = ImageGenerationNode::new(Arc::new(storage)).with_openai_base_url(server.uri());

        let config = json!({
            "provider": "openai",
            "model": "gpt-image-1",
            "api_key": "${__COLMENA_TEST_IMG_GEN_KEY__}",
            "prompt": "x",
        });
        let out = node
            .execute(&HashMap::new(), &config, &mut json!({}), None)
            .await
            .expect("execute ok with env var resolved");
        assert_eq!(out["output"]["images"].as_array().unwrap().len(), 1);

        std::env::remove_var("__COLMENA_TEST_IMG_GEN_KEY__");
    }
}
